<?php

function commerce_delete_cart_menu() {
  $items = array();
  $items['cart/%/delete'] = array(
    'title' => 'Delete Commerce Cart',
    'page arguments' => array(1),
    'page callback' => 'commerce_delete_cart_main',
    'access callback' => TRUE,
  );
  $items['admin/commerce/config/delete-cart-config'] = array(
    'title' => 'Delete Cart Configuration',
    'description' => 'Change the redirect URL after you delete your cart',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_delete_cart_admin'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}


/*
 * Where the magic happens
 */
function commerce_delete_cart_main($uid) {
  // db_delete orders in cart or in checkout process
  // TODO: combine to single delete
  db_delete('commerce_order')
    ->condition('uid', $uid)
    ->condition('status', 'checkout_%', 'LIKE')
    ->execute();
  db_delete('commerce_order')
    ->condition('uid', $uid)
    ->condition('status', 'cart')
    ->execute();

  $defaults = commerce_delete_cart_defaults();
  $redirect_url = variable_get('commerce-delete-cart-redirect', $defaults['commerce-delete-cart-redirect']);
  drupal_goto($redirect_url);
}

/*
 * Settings Form
 */
function commerce_delete_cart_admin() {
  $defaults = commerce_delete_cart_defaults();
  $form = array();
  $form['commerce-delete-cart-redirect'] = array(
    '#type' => 'textfield',
    '#title' => t('Redirect URL'),
    '#default_value' => variable_get('commerce-delete-cart-redirect', $defaults['commerce-delete-cart-redirect']),
    '#description' => t('Change what page a user is taken to after deleting their cart'),
    '#required' => TRUE,
  );
  return system_settings_form($form);
}

function commerce_delete_cart_defaults(){
  $defaults = array();
  $defaults['commerce-delete-cart-redirect'] = 'node'; // by default we will redirect to front page
  return $defaults;
}

